# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f9b1b9654f8e9e7bd9744f4ed905315f8089729f65dc4f9368864bfbf6fd82373d4784d6107539afdcdb55150d146b3d8795452932f499702a82690c4378df56

test:
  secret_key_base: b50e550ae6a2e6511b28f231faa24781ce64479b68b783e7a669796a86f40a4550753876b6792f1c0981f17116447f2a47db897175d4ef7ea2904e82f8622757

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
